# Generated by Django 5.2.6 on 2025-09-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0002_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pose',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/yoga/poses/'),
        ),
    ]
